---
- hosts: kubernetes
  user: root

  tasks:
  - name: deploy regapp on k8s
    command: kubectl apply -f regapp-deploy.yml

  - name: create service for regapp
    command: kubectl apply -f regapp-service.yml
    
  - name: rollout for new update
    command: kubectl rollout restart deployment.apps/user-regapp
